src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class Utilisateur implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Column(nullable: true)]
    private ?string $resetToken = null;

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): void
    {
        $this->resetToken = $resetToken;
    }
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_naissance = null;

    #[ORM\ManyToOne(inversedBy: 'refUtilisateurs')]
    private ?Modele $refModele = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): static
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getRefModele(): ?Modele
    {
        return $this->refModele;
    }

    public function setRefModele(?Modele $refModele): static
    {
        $this->refModele = $refModele;

        return $this;
    }
}

src/Form/UtilisateurType.php
<?php

namespace App\Form;
use App\Entity\Utilisateur;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use App\Entity\Modele;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class UtilisateurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class, ['label' => 'Email'])
            ->add('nom')
            ->add('prenom')
            ->add('ville')
            ->add('date_naissance')
            ->add('roles', ChoiceType::class, [
                'choices' => [
                    'Utilisateur' => 'ROLE_USER',
                    'Pilote' => 'ROLE_PILOTE',
                    'Admin' => 'ROLE_ADMIN',
                ],
                'label' => 'Rôles',
                'multiple' => true,
                'expanded' => true,
            ]);

                $builder->add('refModele', EntityType::class, [
                    'class' => Modele::class,
                    'choice_label' => function (Modele $modele) {
                        return $modele->getMarque() . ' - ' . $modele->getModele();
                    },
                    'label' => 'Modèle',
                    'required' => false,
                ]);

            $builder->add('password', RepeatedType::class, [
                'type' => PasswordType::class,
                'first_options' => ['label' => 'Mot de passe'],
                'second_options' => ['label' => 'Confirmez le mot de passe'],
                'invalid_message' => 'Les mots de passe ne correspondent pas.',
                'mapped' => false // Ce champ n'existe pas dans l'entité User
            ]);

    }
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Utilisateur::class,
        ]);
    }
}

src/Controller/UtilisateurController.php
<?php

namespace App\Controller;

use App\Entity\Utilisateur;
use App\Form\UtilisateurType;
use App\Repository\UtilisateurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
#[Route('/utilisateur')]
final class UtilisateurController extends AbstractController
{
    #[Route(name: 'app_utilisateur_index', methods: ['GET'])]
    public function index(UtilisateurRepository $utilisateurRepository): Response
    {
        return $this->render('utilisateur/index.html.twig', [
            'utilisateurs' => $utilisateurRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_utilisateur_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $passwordHasher): Response
    {
        $utilisateur = new Utilisateur();
        $form = $this->createForm(UtilisateurType::class, $utilisateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Encoder le mot de passe
            $plainPassword = $form->get('password')->getData();
            if ($plainPassword) {
                $encodedPassword = $passwordHasher->hashPassword($utilisateur, $plainPassword); // Utilisation de hashPassword
                $utilisateur->setPassword($encodedPassword); // Assigner le mot de passe encodé
            }

            // Persister l'utilisateur
            $entityManager->persist($utilisateur);
            $entityManager->flush();

            return $this->redirectToRoute('app_utilisateur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('utilisateur/new.html.twig', [
            'utilisateur' => $utilisateur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_utilisateur_show', methods: ['GET'])]
    public function show(Utilisateur $utilisateur): Response
    {
        return $this->render('utilisateur/show.html.twig', [
            'utilisateur' => $utilisateur,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_utilisateur_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Utilisateur $utilisateur, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UtilisateurType::class, $utilisateur);
        $form->remove("submit");
        $form->remove("password");
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_utilisateur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('utilisateur/edit.html.twig', [
            'utilisateur' => $utilisateur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_utilisateur_delete', methods: ['POST'])]
    public function delete(Request $request, Utilisateur $utilisateur, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$utilisateur->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($utilisateur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_utilisateur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/utilisateur/_delete_form.html.twig
<form method="post" action="{{ path('app_utilisateur_delete', {'id': utilisateur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ utilisateur.id) }}">
    <div class="text-center">
        <button class="btn btn-primary">Delete</button>
    </div>
</form>

templates/utilisateur/_form.html.twig
{# templates/utilisateur/_form.html.twig #}

{{ form_start(form) }}
<div class="form-container">
    <table class="table">
        <tr>
            <th>{{ form_label(form.email) }}</th>
            <td>{{ form_widget(form.email) }}</td>
        </tr>
        <tr>
            <th>{{ form_label(form.roles) }}</th>
            <td>{{ form_widget(form.roles) }}</td>
        </tr>
        <tr>
            <th>{{ form_label(form.refModele) }}</th>
            <td>{{ form_widget(form.refModele) }}</td>
        </tr>
        <tr>
            <th>{{ form_label(form.nom) }}</th>
            <td>{{ form_widget(form.nom) }}</td>
        </tr>
        <tr>
            <th>{{ form_label(form.prenom) }}</th>
            <td>{{ form_widget(form.prenom) }}</td>
        </tr>
        <tr>
            <th>{{ form_label(form.ville) }}</th>
            <td>{{ form_widget(form.ville) }}</td>
        </tr>
        <tr>
            <th>{{ form_label(form.date_naissance) }}</th>
            <td>{{ form_widget(form.date_naissance) }}</td>
        </tr>
    </table>

    <div class="form-group text-center">
        <button type="submit" class="btn btn-primary">Enregistrer</button>
    </div>
</div>
{{ form_end(form) }}

templates/utilisateur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Utilisateur{% endblock %}

{% block body %}
    <div class="white-box">
        <h1 class="text-center">Modification de {{ utilisateur.email }}</h1>

        {# Inclusion du fichier _form.html.twig pour le formulaire et son bouton submit #}
        {% include 'utilisateur/_form.html.twig' with {'form': form} %}
        <br>
        {{ include('utilisateur/_delete_form.html.twig') }}

        <a href="{{ path('app_utilisateur_index') }}">Retour à la liste</a>
    </div>
{% endblock %}

templates/utilisateur/index.html.twig
{% extends 'base.html.twig' %}

 {% block title %}Utilisateur index{% endblock %}

 {% block body %}
     <div class="white-box">
         <h1 class="text-center">Vue de tout les Utilisateurs</h1>
         <table class="table">
             <thead>
             <tr>
                 <th>Id</th>
                 <th>Email</th>
                 <th>Roles</th>
                 <th>Modèle</th>
                 <th>Nom</th>
                 <th>Prenom</th>
                 <th>Ville</th>
                 <th>Date_naissance</th>
                 <th>actions</th>
             </tr>
             </thead>
             <tbody>
             {% for utilisateur in utilisateurs %}
                 <tr>
                     <td>{{ utilisateur.id }}</td>
                     <td>{{ utilisateur.email }}</td>
                     <td>{{ utilisateur.roles ? utilisateur.roles|json_encode : '' }}</td>
                     <td>
                         {% if 'ROLE_PILOTE' in utilisateur.roles and utilisateur.refModele %}
                             {{ utilisateur.refModele.marque ~ ' - ' ~ utilisateur.refModele.modele }}
                         {% else %}
                             Non Pilote
                         {% endif %}
                     </td>
                     <td>{{ utilisateur.nom }}</td>
                     <td>{{ utilisateur.prenom }}</td>
                     <td>{{ utilisateur.ville }}</td>
                     <td>{{ utilisateur.dateNaissance ? utilisateur.dateNaissance|date('Y-m-d') : '' }}</td>
                     <td>
                         <a href="{{ path('app_utilisateur_show', {'id': utilisateur.id}) }}">Voir</a>
                         <a href="{{ path('app_utilisateur_edit', {'id': utilisateur.id}) }}">Modifier</a>
                     </td>
                 </tr>
             {% else %}
                 <tr>
                     <td colspan="9">no records found</td>
                 </tr>
             {% endfor %}
             </tbody>
         </table>

         <a href="{{ path('app_utilisateur_new') }}">Nouveau</a><br>
         <a href="{{ path('app_admin') }}">Retour à la page d'accueil Admin</a>
     </div>
 {% endblock %}

templates/utilisateur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Utilisateur{% endblock %}

{% block body %}
    <div class="white-box">
        <h1 class="text-center">Nouvel Utilisateur</h1>
        {{ form_start(form) }}
        <table class="table">
            <tr>
                <th>{{ form_label(form.email) }}</th>
                <td>{{ form_widget(form.email) }}</td>
            </tr>
            <tr>
                <th>{{ form_label(form.roles) }}</th>
                <td>{{ form_widget(form.roles) }}</td>
            </tr>
            <tr>
                <th>{{ form_label(form.refModele) }}</th>
                <td>{{ form_widget(form.refModele) }}</td>
            </tr>
            <tr>
                <th>{{ form_label(form.nom) }}</th>
                <td>{{ form_widget(form.nom) }}</td>
            </tr>
            <tr>
                <th>{{ form_label(form.prenom) }}</th>
                <td>{{ form_widget(form.prenom) }}</td>
            </tr>
            <tr>
                <th>{{ form_label(form.ville) }}</th>
                <td>{{ form_widget(form.ville) }}</td>
            </tr>
            <tr>
                <th>{{ form_label(form.date_naissance) }}</th>
                <td>{{ form_widget(form.date_naissance) }}</td>
            </tr>
            <tr>
                <th>{{ form_label(form.password.first) }}</th>
                <td>{{ form_widget(form.password.first) }}</td>
            </tr>
            <tr>
                <th>{{ form_label(form.password.second) }}</th>
                <td>{{ form_widget(form.password.second) }}</td>
            </tr>
        </table>

        <div class="text-center">
            <button type="submit" class="btn btn-primary">Créer</button>
        </div>
        {{ form_end(form) }}

        <div class="mt-3">
            <a href="{{ path('app_utilisateur_index') }}">← Retour à la liste</a>
        </div>
    </div>
{% endblock %}

templates/utilisateur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur{% endblock %}

{% block body %}
    <div class="white-box">
        <h1 class="text-center">Information de {{ utilisateur.email }} </h1>
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ utilisateur.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ utilisateur.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ utilisateur.roles ? utilisateur.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Modèle</th>
                <td>
                    {% if 'ROLE_PILOTE' in utilisateur.roles and utilisateur.refModele %}
                        {{ utilisateur.refModele.marque ~ ' - ' ~ utilisateur.refModele.modele }}
                    {% else %}
                        Non Pilote
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ utilisateur.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ utilisateur.prenom }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ utilisateur.ville }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ utilisateur.dateNaissance ? utilisateur.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>
        {{ include('utilisateur/_delete_form.html.twig') }}

        <a href="{{ path('app_utilisateur_edit', {'id': utilisateur.id}) }}">Modifier</a>
        <br>
        <a href="{{ path('app_utilisateur_index') }}">← Retour à la liste</a>


    </div>
{% endblock %}